// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_p1OX-XRPLmBN8VmYc_9cndKc0mh38c',
    appId: '1:530439933486:web:144a559a09e5cb1961d9bf',
    messagingSenderId: '530439933486',
    projectId: 'fotograf-eslestirme-oyunu',
    authDomain: 'fotograf-eslestirme-oyunu.firebaseapp.com',
    storageBucket: 'fotograf-eslestirme-oyunu.appspot.com',
    measurementId: 'G-3HJ5NWXWJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfY5kBI3zc7sEpEOpH8F5ookJgudjyYh8',
    appId: '1:530439933486:android:4a8f13c5d444a04161d9bf',
    messagingSenderId: '530439933486',
    projectId: 'fotograf-eslestirme-oyunu',
    storageBucket: 'fotograf-eslestirme-oyunu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KPPCefYa5AgCggs-b4Zdh06yoVKCskc',
    appId: '1:530439933486:ios:a102905531970e0361d9bf',
    messagingSenderId: '530439933486',
    projectId: 'fotograf-eslestirme-oyunu',
    storageBucket: 'fotograf-eslestirme-oyunu.appspot.com',
    iosBundleId: 'com.yasir.derbent.fluttergame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KPPCefYa5AgCggs-b4Zdh06yoVKCskc',
    appId: '1:530439933486:ios:fb3217f132e72abf61d9bf',
    messagingSenderId: '530439933486',
    projectId: 'fotograf-eslestirme-oyunu',
    storageBucket: 'fotograf-eslestirme-oyunu.appspot.com',
    iosBundleId: 'com.yasir.derbent.fluttergame.RunnerTests',
  );
}
